/*
 * $HIVE — single source of truth for every address the site reads. GENERATED by wire-launch.mjs.
 * Both dashboard.html and stake.html load this first and merge it over their defaults.
 */
window.HIVE_CFG = {
  hiveToken:    "0xCdaE63D95D6dd4f89f6e508c77bD4388b4e5C8Ab",
  curve:        "0x27929453cDf906F3B536C2519621746bF417F890",
  hiveStaking:  "0x4a56860781f90Cd4d9D9883b33c2B9bE94E88695",
  seatVault:    "",

  splitter:     "0xCFd95537953236E7885f450F001b00960F496bC2",
  potWallet:    "0x84b31CB3D205EfD2d20F29eA7ccaB1bc34326DdB",
  imdRobinhood: "0x5F7Bb59365ce557C26dbcAa4EE9d39A4b95B7127",
  identityMd:   "0x0000eC93127BAA929E58E97dd0095A2BFb38ec1D",
  imdEth:       "0xD34a99Bc0f67aE1bbd63C660e6d0b0dd03E263B7",
  simdVault:    "0x9Efa934D9fAd4AE28c998a40195646b965a97247",

  chainId: 4663,
  chainHex: "0x1237",
  rpc: "https://rpc.mainnet.chain.robinhood.com",
  rhRpcs:  ["https://rpc.mainnet.chain.robinhood.com", "https://rpc.ordofi.network"],
  ethRpcs: ["https://ethereum-rpc.publicnode.com", "https://eth.llamarpc.com", "https://rpc.ankr.com/eth"],
  explorer: "https://robinhoodchain.blockscout.com",
  chainName: "Robinhood Chain"
};
